name: Test Without gif jpeg svg
on: push

jobs:
  Linux:
    name: Node.js 14 on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install basic deps
        run: sudo apt-get install libcairo2-dev libpango1.0-dev

      - name: Check with ldconfig
        run: ldconfig -p 2>/dev/null | grep -E gif
      - name: Check with gcc
        run: gcc -lgif || 0
      - name: Check with pkg-config
        run: |
          pkg-config --cflags gif || 0
          pkg-config --libs gif || 0
      - name: List installed packages
        run: |
          apt list --installed | grep gif

      - name: Build
        run: |
          cd ..
          mkdir ghtemptest
          cd ghtemptest
          npm install canvas
          node -p "require('canvas')"
